server:
  port: 8080
  servlet:
    context-path: /

spring:
  batch:
    job:
      enabled: false
  application:
    name: CarRentProject
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 180000
      maximum-pool-size: 2
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
      jdbc-url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
      username: sa
  jpa:
    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
